apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: helm-rabbitmq-cluster-operator
spec:
  package: ghcr.io/hops-ops/helm-rabbitmq-cluster-operator:{{ .Values.version }}
{{- if .Values.skipDependencyResolution }}
  skipDependencyResolution: true
{{- end }}
{{- if .Values.skipDependencyResolution }}
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: hops-ops-helm-rabbitmq-cluster-operatorrender
spec:
  package: ghcr.io/hops-ops/helm-rabbitmq-cluster-operatorrender:{{ .Values.version }}
{{- end }}
